### ISSUE TITLE
Clipper and Importer yield different size grids

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#10]
I have produced temp, precip, and snodas grids using `vortex`.  The precip and temp data sets have the same extents:

![image](https://user-images.githubusercontent.com/11522898/91192808-63c42980-e6c4-11ea-80c7-8f3e22b02df0.png)

![image](https://user-images.githubusercontent.com/11522898/91192851-6d4d9180-e6c4-11ea-8d35-30d25e767cd7.png)

The SNODAS grids have a different origin.

![image](https://user-images.githubusercontent.com/11522898/91192908-80606180-e6c4-11ea-9cba-2b756d3fa49a.png)

Can Vortex be used to align these datasets?

**Comment by tombrauer** [comment]
How did you arrive at these grids? If you used the importer with the same clipping datasource, the extents should be the same. You could always try creating a shapefile that bounds the smallest grid, in this case SNODAS, then clip the other grids with it.

**Comment by danhamill** [comment]
I used the same shapefile.  After more testing, clipping using the importer yields a smaller grid than clipping from the importer.

**Clipped using Importer**
![image](https://user-images.githubusercontent.com/11522898/91215444-8402e100-e6e2-11ea-95f9-584645f02e19.png)

**Clipped using Clipper**
![image](https://user-images.githubusercontent.com/11522898/91215598-bad8f700-e6e2-11ea-81e0-f698440af7a1.png)

[dss_exports.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/5125775/dss_exports.zip)

**Comment by tombrauer** [comment]
Ok, good to know. It looks like the `clipper` result has a rounding error. I will try to clean that up. The two use different algorithms since the `importer` also includes functionality to resample for grid cell size and CRS. I'd stick with clipping via the importer tool until a fix is in place.

**Comment by danhamill** [comment]
I've been there.  Thanks!

**Comment by tombrauer** [comment]
@danhamill I was able to reproduce the issue with a dataset of my own and implement a fix. If you don't mind testing with your dataset I would appreciate it. Fixed in version is v.0.10.1: https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.10.1

**Comment by danhamill** [comment]
Great.  I have a dataset I need to work up.  I’ll let you know the results.  

Nice work!
nnk2193 <notifications@github.com> wrote:
“@danhamill I was able to reproduce the issue with a dataset of my own and implement a fix. If you don't mind testing with your dataset I would appreciate it. Fixed in version is v.0.10.1: https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.10.1”

**Comment by danhamill** [comment]
Clipper yields the correct extents now!  :rocket: :rocket: :rocket: :rocket:
