### ISSUE TITLE
Grid to point converter gives a time series of integers

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#11]
When I use the grid to point utility, I get a time series of integer values.  

Here is shapefile:
[Willow_Creek.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/5132917/Willow_Creek.zip)

Here is a DSS file with grids
[input_dss_grids.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/5132925/input_dss_grids.zip)

Here is a file with the expected results
[Expected_Zonal_Stats.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/5132933/Expected_Zonal_Stats.zip)

Shouldn't the zonal statistics be floats?

**Comment by tombrauer** [comment]
Dan, can you send the dss grids again? I'm not sure what happened with them but the zip is empty. You can also send via the HEC dropbox or via MS Teams.

**Comment by danhamill** [comment]
I'll try again tomorrow.   I've had other problems with uploading zip archives lately.

**Comment by danhamill** [comment]
How about this upload.

[Input_Dss_Grids.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/5142485/Input_Dss_Grids.zip)

**Comment by tombrauer** [comment]
Good deal, I have the grids now. I wonder if there's a expiry on file exchanges...

I'll let you know what I find, once I get a chance to dig in.

**Comment by tombrauer** [comment]
I ran the `grid-to-point-converter` with your dataset. I spot checked a few values with you expected values spreadsheet and the values look really similar (screen cap below). Good to know.

![image](https://user-images.githubusercontent.com/9610094/91624037-fa0d7f00-e952-11ea-9dbb-dd6385488c4d.png)

I wasn't able to reproduce the integer time-series issue. Maybe you have a bad version of HEC-DSS?

**Comment by danhamill** [comment]
Hmm.  Maybe it is my version of dss.  I’ve been bouncing between 3.0.00.212 and 2.6.   I’ll check tomorrow.  


Your results appear correct to me.  I’ll report back.  Thanks for checking!
nnk2193 <notifications@github.com> wrote:
“I ran the grid-to-point-converter with your dataset. I spot checked a few values with you expected values spreadsheet and the values look really similar (screen cap below). Good to know.”

[image]
“I wasn't able to reproduce the integer time-series issue. Maybe you have a bad version of HEC-DSS?”

**Comment by tombrauer** [comment]
@ktarbet can you get @danhamill a new build of HEC-DSSVue? I am working with v.3.0.1.125

**Comment by danhamill** [comment]
Confirmed the version 3.0.00.22 is a wonky version of DSS.  When I review the `grid to point` results in dss 2.6, I am seeing an output similar to your demonstration.

**Comment by tombrauer** [comment]
Ok, good to know. Be careful with the 3.* DSSVue builds. They are all unofficial and are all broken in one way or another. I will say - I've been v.3.0.1.125 for about a month now, and haven't found any bugs 🤞

**Comment by danhamill** [comment]
I think the only reason 3.0.00.22 was on my radar was because you could directly import soil moisture data from snotel.

**Comment by tombrauer** [comment]
Snotel should be a plugin. If that's the case you can drag and drop it into any DSS build.
![image](https://user-images.githubusercontent.com/9610094/91640897-bdcf3280-e9d5-11ea-8e21-442f25a4c7d9.png)

**Comment by danhamill** [comment]
:shipit::shipit::shipit::shipit:

**Comment by ktarbet** [comment]
> @ktarbet can you get @danhamill a new build of HEC-DSSVue? I am working with v.3.0.1.125

yes, on the way.

**Comment by danhamill** [comment]
@ktarbet  Thank you, download received.  

I downloaded and extracting the new build of DSS, I am having the same issue.   I found if i change the precision in tabulate, i see the additional digits.  Where can I globally set the tabular precision?  I cant seem to find any menus for default program settings.

**Comment by ktarbet** [comment]
I see the same issue,  the number of decimals selected is not saved between tables.  I've added this to our internal Issue tracker.

![image](https://user-images.githubusercontent.com/4818531/91758460-eb0e1300-eb84-11ea-92d5-f21765f9d2da.png)

**Comment by danhamill** [comment]
That't the menu I found too.  Is there a way to export the data to excel with the desired precision?

**Comment by ktarbet** [comment]
@danhamill  The export should be including all decimal places in the floating  point number.   In Excel you can format to desired style.
