### ISSUE TITLE
dss is creating wrong

### ISSUE THREAD

**Issue by Gauravfouzdar** [HydrologicEngineeringCenter/Vortex#110]
the created input is showing incorrect start time and end time

**Comment by tombrauer** [comment]
@Gauravfouzdar please provide more information.

**Comment by Gauravfouzdar** [comment]
![Screenshot 2024-05-30 205840](https://github.com/HydrologicEngineeringCenter/Vortex/assets/119810464/3d533945-8e1a-47cd-9ec8-f5cbfae39cac)

see the start time and end time

**Comment by tombrauer** [comment]
@Gauravfouzdar I don't see any issue in the screen capture you have provided. Maybe you need to use the time-shifter to shift the start time or end time.

**Comment by Gauravfouzdar** [comment]
thanks time shifter worked
