### ISSUE TITLE
Current version importer writes both MRMS and AORC precipitation fields with same D and E part timesteps

### ISSUE THREAD

**Issue by openSourcerer9000** [HydrologicEngineeringCenter/Vortex#113]
I'm including datasets from both of these sources  for you to test. It seems it's been doing this for the last ~ dozen versions. I've found versions that  write the time steps correctly but have a plethora of other bugs, such as writing blank DSS grids or simply freezing up indefinitely. Unfortunately I don't have exact version numbers for each bug documented. 

I've tried playing with the metadata etc  but with no luck. When running time shifter on these DSS's, E part drops out completely.
Using 'dataType':'PER-CUM','units':'MM', Cpart:'PRECIPITATION' cellsize 1000

![image](https://github.com/HydrologicEngineeringCenter/Vortex/assets/61931826/16120f18-0598-46fd-b4b4-afa7b42aac49)
[March_2018 MRMS.zip](https://github.com/user-attachments/files/16090289/March_2018.MRMS.zip)
[AORC.zip](https://github.com/user-attachments/files/16090546/AORC.zip)

**Comment by tombrauer** [comment]
It looks like you are trying to import a non-[CF compliant](https://daac.ornl.gov/submit/netcdfrequirements/) NetCDF file. If the NetCDF file doesn't include a `time_bnds` variable, which defines the interval over which the data applies, vortex doesn't make any guesses about what that might be. For this case data processing happens in two steps 1) Use the importer to import the data to HEC-DSS and 2) use the time-shifter to shift the start time or end time of the HEC-DSS grids by some amount, e.g. shift the start time by -1 hours. I would contact the originator of the data and ask them to include a `time_bnds` variable to be more explicit about the data interval.

**Comment by openSourcerer9000** [comment]
Thanks, I've never heard of that one. I'm assuming that should be an auxiliary coordinate variable, not a second data variable next to precipitation? Do you have an example dataset with time_bnds so I can see what dims, coordinates, and attributes it would have? My data is cumulative hourly precipitation depth.

**Comment by openSourcerer9000** [comment]
NVMD, I didn't see your link. Works like a charm
