### ISSUE TITLE
Dataset Support: UA SWE

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#13]
It would be nice if `vortex` could support the University of Arizona's SWE and snow depth data .  The data are located:

https://climate.arizona.edu/data/UA_SWE/

U of A has assembled the data in NETCDF format.  `importer` seems to parse the time series, but the dss grids are all zeros.  The logging information indicates there was a buffer error before each `ZWRITE` print out.

```
ERROR 1: Buffer is too small
 -----DSS---ZWRITE Unit    3; Vers.    1:  /SHG/WILLOW CREEK/SWE/28DEC2017:1200/29DEC2017:1200/UA_V2/
```

**Comment by tombrauer** [comment]
@danhamill I just updated some logic to accommodate the UA SWE dataset. Fixed-in version is 0.10.3: https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.10.3

**Comment by danhamill** [comment]
Thanks!  We have found the UA dataset as good alternative to SNODAS,  He seems to near real-time production on that server.  Maybe we can get Brett to include it in cumulus someday.

**Comment by danhamill** [comment]
Any ideas why it wont read a daily grid?  The dss time stamp is wonky after you run `importer`

[2020_03_22.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/5219161/2020_03_22.zip)

When I open it using the python library `rioxarray` it complains about `time_str`, but after inspection everything looks fine.

**Comment by tombrauer** [comment]
I'm not sure that the date handling in the netcdf library was getting it right. The start date was double from what it should have been, i.e. 2140 instead of 2020 referenced from 1900. I think this being a single grid without grids before or after it might have confused the netcdf library logic. I added special date-handling logic for this dataset.

**Comment by danhamill** [comment]
Great, thanks!
