### ISSUE TITLE
'grid_to_point.exe' launches clipper

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#17]
Hey Tom,

A co-worker of mine found another bug.  If you launch `grid_to_point` from the executable, it pulls up `clipper`  shapefile selecting menu.  

![image](https://user-images.githubusercontent.com/11522898/94036246-1950ce00-fd92-11ea-9f17-508cea8e19bc.png)

It should look like:

![image](https://user-images.githubusercontent.com/11522898/94036372-3d141400-fd92-11ea-92d9-5b9e1b2cef03.png)

If you launch `grid_to_point` from the `.bat` file, everything works as expected.

Dan

**Comment by tombrauer** [comment]
Thanks for letting me know. The *.exe was launching the wrong *.jar. Fixed in v.0.10.6. https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.10.6
