### ISSUE TITLE
Batch processing  multiple grid data to create timeseries in grid to point converter

### ISSUE THREAD

**Issue by Shamsalamin** [HydrologicEngineeringCenter/Vortex#19]
I am trying to create a DSS timeseries out of 24 GRIB format hourly precipitation files. using the grid to point converter. I don't seem to able to add more than 1 file at a time. Is it possible to add mutliple grib files and generate the timeseries using this utility? 
Thanking you in anticipation.

**Comment by tombrauer** [comment]
Hello @Shamsalamin,

The `grid-to-point-converter` is working under the premise that you have one file with many internal gridded records. This is common for HEC-DSS and NetCDF file formats, but not as common with GRIB. I recommend using the `importer` utility to read your grids into HEC-DSS format, then using the `grid-to-point-converter` utility to convert the gridded DSS records to point time-series.

**Comment by Shamsalamin** [comment]
Hi @tombrauer ,
Thanks! That did work. One thing though- I noticed when I was trying to use the importer plugin to import the whole grid file it was showing empty DSS (after using the grid to point plugin). But when I used the clipping option using a shape file in the Importer  step and then used the grid to point it went smoothly. Nonetheless, definitely a great tool and timesaver for what we are trying to do.

**Comment by tombrauer** [comment]
If you're not already, I recommend using a v.3.* build of HEC-DSSVue. You can download here: https://www.hec.usace.army.mil/software/hec-dssvue/downloads/dev/

Hopefully that fixes the empty grid issue. If there is something else going on, feel free to report.
