### ISSUE TITLE
asc format 

### ISSUE THREAD

**Issue by PowIlove** [HydrologicEngineeringCenter/Vortex#34]
@tombrauer  i was working in vortex again and i was wondering if this tool supports other formats such as .asc i wanted to do some tests with it but I got this error

![image](https://user-images.githubusercontent.com/59849903/122106520-e098cf00-cdce-11eb-8d04-e9899d5dc202.png)

**Comment by tombrauer** [comment]
@PowIlove is there a *.prj file to accompany the *.asc file? From the stack trace it looks like the code is not finding a spatial reference.

**Comment by PowIlove** [comment]
good morning @tombrauer I did not accompany the asc with a prj, the truth was I did not know that it was necessary, I will take it into account, I believed that only place the asc

**Comment by hahabibi88** [comment]
@PowIlove I am trying to import several asci format rainfall data to dss. The data is in 15 minutes time interval. The importer.exe works just fine and convert the data to dss but it doesn't fill out Part D and part E of dss file which are related to Start and End time. Is there any specific file name that you used to import ASC format? Thank you!

**Comment by PowIlove** [comment]
hello @hahabibi88 You know that I am also having the same problem at the moment, and I have not found the solution to this, as soon as I find something I will inform you. regards
