### ISSUE TITLE
asc Format-File names

### ISSUE THREAD

**Issue by hahabibi88** [HydrologicEngineeringCenter/Vortex#36]
I am trying to import several asci format rainfall data (not PRISM) to dss. The data is in 15 minutes time interval. The importer.exe works just fine and convert the data to dss but it doesn't fill out Part C, D and part E of dss file which are related to variable (like precipitation), and Start and End time. Is there any specific file name that I should use for asci format data? Thank you!

**Comment by joshuarwillis** [comment]
@hahabibi88 just make sure that the file names (.asc and .prj) contain the start time and end time in format "yyyy_MM_dd't'Hmm". For example, "2018_01_01t1100_2018_01_01t1115.asc" should import correctly.

**Comment by hahabibi88** [comment]
@joshuarwillis Thank you, Worked! Could you also let me know how to include "PRECIPITATION" in the Part C? should "ppt" included in a spatial way in the .asc and .prj filename?

**Comment by joshuarwillis** [comment]
@hahabibi88 glad it worked. It doesn't look like there is a way to include PRECIPITATION as the C Part with your dataset currently. Do you mind sharing the source of your precipitation grids? We may be able to make improvements in future releases so that Vortex better handles other precipitation sources.

**Comment by tanveerahmed-89** [comment]
Dear good people, hope everyone is doing well. I am trying to follow the example provided for 15-minutes time interval and replicate the things for 1-hr time interval by changing the naming format of the ascii files like this: "2016_08_12t1200_2016_08_12t1300.asc". The importer.exe was able to convert the data into dss but unfortunately when I was trying to plot the data, the Grid Display is blank. (I have attached an image for your reference).

The same ascii file works if I just follow the naming format for 15-minutes time interval as: "2016_08_12t1100_2016_08_12t1115.asc". Is there any specific format that should be followed for 1-hr time interval? 

I have also attached the ascii files I am working with for your reference. Any suggestions will be much appreciated. 
[ASCII_Files_TA_20210907.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/7123796/ASCII_Files_TA_20210907.zip)
Thank you.

![15_min_time_interval](https://user-images.githubusercontent.com/90053240/132397179-4347d64e-2b75-4b40-ba24-06a46a535511.jpg)

![1_hr_time_interval](https://user-images.githubusercontent.com/90053240/132397145-68ba6cc9-96a1-4ec5-9921-15c01ae3810c.jpg)

**Comment by hahabibi88** [comment]
@tanveerahmed-89 I think you need to remove the "00" for the minute part. It probably will work with this format for 1-hr intervals: "2016_08_12t12_2016_08_12t13". try it.

**Comment by tanveerahmed-89** [comment]
@hahabibi88 thank you very much for your suggestion. I tried it. It solves the issue for grid display but now part D and part E i.e. "timestamp" of the DSS file are empty. If you have any other idea will be glad to know and try. Appreciate your help.

![image](https://user-images.githubusercontent.com/90053240/132414614-b180bbba-9944-4124-ad0c-99de52428b43.png)

**Comment by hahabibi88** [comment]
@tanveerahmed-89 I just tested with "00", it is working, see the image bellow!
![image](https://user-images.githubusercontent.com/47610832/132921348-61b1471a-708b-4869-ac55-fe2dd59ea9b6.png)

This is the file name, I tried. 
2016_08_12t1200_2016_08_12t1300.asc
2016_08_12t1200_2016_08_12t1300.prj

**Comment by hydrouser** [comment]
> 
> 
> @tanveerahmed-89 I just tested with "00", it is working, see the image bellow! ![image](https://user-images.githubusercontent.com/47610832/132921348-61b1471a-708b-4869-ac55-fe2dd59ea9b6.png)
> 
> This is the file name, I tried. 2016_08_12t1200_2016_08_12t1300.asc 2016_08_12t1200_2016_08_12t1300.prj

I have really no explanation, why import works for some file names (e.g. the files cited above). I change the filename to "1999_08_12t1200_1999_08_12t1300" and filling part D and part E won't work anymore. 
Is there any workaround?
Thanks for the effort

**Comment by danhamill** [comment]
I tried the suggested `2016_08_12t1200_2016_08_12t1300.tif` file name structure for a GTIFF file and could not get the partD/PartE to populate correctly.  I ended up finding you an add `precip_` as a prefix to the start and end dates for the grid worked.  Something like: `precip_2016_08_12t1200_2016_08_12t1300.tif`

This is similar to #18

**Comment by tombrauer** [comment]
Hopefully this [documentation](https://github.com/HydrologicEngineeringCenter/Vortex/wiki/Raster-Filename-Parsing) helps clarify expectations for date parsing in file names.

**Comment by tombrauer** [comment]
Marking as closed.
