### ISSUE TITLE
Gradle build missing task in Vortex root

### ISSUE THREAD

**Issue by msgthrows** [HydrologicEngineeringCenter/Vortex#45]
Hello, 
I thought the issues were on my end when building the API, but there is nothing left to try on my end. I am getting the following message on a Windows 10 computer and looking at the Vortex folder I can't find any reference to "final" other then the build file. It seems to be missing.
"""
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\\[ME]\Vortex-master\build.gradle.kts' line: 384

* What went wrong:
Task with name 'final' not found in root project 'vortex'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
"""

**Comment by tombrauer** [comment]
The `final` task should be coming in with the `nebula-release` plugin that is declared in the `plugins` block at the top of the build script. It is as if the plugin is not correctly loading on your system. You could try a `gradlew --refresh-dependencies` or clearing the gradle cache to see if that resets the plugin.

As a work around you could comment out the lines that depend on the `nebula-release` tasks which currently looks like 384-386.

**Comment by msgthrows** [comment]
Thanks! Looks like there were a couple package updates needed on the first test, but it looks like it is working!

**Comment by tombrauer** [comment]
Ok, good to know!
