### ISSUE TITLE
Surface Pressure Grid Import

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#5]
I have been using `importer` to import RTMA pressure grids.   It appears that the c part is assumed to be `PRECIPITATION`.  Can you guys set up the `.grib2` extension to read the c-part from `GRIB-COMMENT`?

Or, can you make the c-part field editable during the import dialogs?

I am using `voretx 0.9.2`

**Comment by tombrauer** [comment]
It looks like the "pr" in pressure caused the logic to jump into the branch statement for precipitation. "pr" is sometimes given as the variable for precipitation rate. I just made fix to better handle pressure and published a new release: https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.9.3-rc.1

We don't have any C-Part or units conventions in HMS for pressure so I went with "PRESSURE" and "PA". 
https://www.hec.usace.army.mil/confluence/display/HMSUM/.Grid+Data+v4.6

Also - If you want to batch update the A/B/C/F parts or units for grids, you can use the last step of the `sanitizer` utility. I originally set the `sanitizer` up to filter negative precip values but it has some other utility as well.

Let me know how it goes!

**Comment by danhamill** [comment]
@tombrauer c-part name "pressure" seems good.  Is "PA" a shorthand or is if for pascal units?  Tested the new release and everything seems in order.

**Comment by tombrauer** [comment]
@danhamill Yes - I used "PA" for Pascal. I checked the HMS code base today. I looks like I got the C-Part of "PRESSURE" right but kilopascal, "KPA," is actually the preferred unit for pressure. Uploading a 0.9.3-rc.2 build with the update now.

**Comment by danhamill** [comment]
Will this utility convert from Pa to kPa?  The RTMA grids have a native unit of Pa, so somehow I need to convert.  Is there another utility in `vortex` that can perform this calculation before `importer` ?.

**Comment by tombrauer** [comment]
You can do it, but it's a little clunky. The `transposer` utility has a scale factor option. So you could scale grids by 0.001. The `sanitizer` has ability to override DSS units. So you could convert existing grids from "PA" to "KPA". Personally, I'd probably re-import.

**Comment by danhamill** [comment]
I don't understand how `sanitizer` works.  Does it use data already in DSS or will it perform raster math on individual raster datasets ( i.e. .tif, .grib, etc.)?

If its the former, I am also hesitant to rely on an internal dss conversion.

**Comment by tombrauer** [comment]
All of the vortex tools read data into an in-memory object, do operations, then write out. Several readers have been implemented, e.g. DSS, ASC, NetCDF. The only writer implementation is DSS. So, it shouldn't matter which format the data is read in from.
