### ISSUE TITLE
Java.io filenotfoundexception in NLDAS file 

### ISSUE THREAD

**Issue by PowIlove** [HydrologicEngineeringCenter/Vortex#52]
Hello @tombrauer nice to meet you again, i'm having problems again with tools vortex, in this ocassion, i'm working with NLDAS files but the moment to use the tools, appear this mistake:
[mistake vortex.txt](https://github.com/HydrologicEngineeringCenter/Vortex/files/7715351/mistake.vortex.txt)
i put all the line of text tha appear in the code in a notepad file.

**Comment by tombrauer** [comment]
Hi @PowIlove 
Troubleshooting measures:
1. Does `C:\Users\jesus\OneDrive\Documents\Bases de datos\NTFC_ONE DAY\NLDAS_FORA0125_H.A20110818.1000.002.grb.SUB.grb` exist on your machine?
2. Try moving your grib file to a location like `C:/Temp/NLDAS_FORA0125_H.A20110818.1000.002.grb.SUB.grb`

**Comment by PowIlove** [comment]
thanks so much already i can to get the files, i will close the topic
