### ISSUE TITLE
Include batch import "write options" in importer.exe

### ISSUE THREAD

**Issue by RandomPunter** [HydrologicEngineeringCenter/Vortex#56]
Hi @tombrauer,
Being in Australia, all of my raster data is non-standard, from a Vortex point of view. It would seem that the batch import functionality offers a solution in that I could invoke the various write options for my data. Apart from not being great with scripting (although I'm sure I could unpuzzle it given sufficient time), my work PC is locked down tight and it is not possible to get Jython installed, and so this avenue is currently closed to me. 
Is there a possibility of including the full set of write options functionality in importer.exe?

**Comment by tombrauer** [comment]
Hi @RandomPunter - Have you tried running your data through importer.exe? We've tested on so many datasets over the years sometimes it is surprising what it gets right, even if the data is non-standard. If it doesn't bring it in, I'd be curious to see how far off it is.

**Comment by RandomPunter** [comment]
Thanks for the prompt reply. Yes, I have tested many different kinds of file name permutations on .asc and .tif. Generally what happens is that the importer does not recognise a common variable (in my case, "precip"), and so each file is imported separately. 

![image](https://user-images.githubusercontent.com/98135176/150464311-c86cc741-a5d2-4f1f-85e0-362457b6d39d.png)

![image](https://user-images.githubusercontent.com/98135176/150464338-aedf2daa-92f3-4f65-b102-7f6f44d169c1.png)

![image](https://user-images.githubusercontent.com/98135176/150464401-4901fe4e-6323-4f50-b28c-77685a6f55aa.png)

**Comment by tombrauer** [comment]
This actually looks correct. Each tif file translates to a gridded record within the DSS file. To make HEC-HMS happy, you can batch rename the C Part in HEC-DSSVue by selecting all of the files, right-click, rename. You might also try the [v0.10.27-rc.2](https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.10.27-rc.2) build I just posted which should auto-extract the DSS C Part from the file name.
