### ISSUE TITLE
Error converting Grib2 to DSS using vortex scripts

### ISSUE THREAD

**Issue by tharunpalla** [HydrologicEngineeringCenter/Vortex#59]
Hi, 

I am trying to convert grib2 rainfall data to DSS format. I have written a script to fetch the grib2 files from 'https://nomads.ncep.noaa.gov/cgi-bin/filter_nam_conusnest.pl?dir=%2Fnam.20220204' and then used vortex to convert to DSS files. 

I am currently getting the following error:

![image](https://user-images.githubusercontent.com/20412132/152624810-ad51abeb-db18-43b6-9170-d9f753a837ac.png)

Attaching my code to fetch and convert to DSS files.

[grib2_to_dss_convertor.txt](https://github.com/HydrologicEngineeringCenter/Vortex/files/8007169/grib2_to_dss_convertor.txt)
[get_current_data.txt](https://github.com/HydrologicEngineeringCenter/Vortex/files/8007170/get_current_data.txt)

**Comment by tombrauer** [comment]
@tharunpalla Did you test importing a sample file using the vortex user interface prior to attempting to script?

**Comment by tharunpalla** [comment]
> @tharunpalla Did you test importing a sample file using the vortex user interface prior to attempting to script?

Yes, I had imported using the interface prior running via script.

**Comment by tombrauer** [comment]
If the user interface works, and the script does not, there is likely an issue with your script. Can you upload a sample of your data?

**Comment by tharunpalla** [comment]
> If the user interface works, and the script does not, there is likely an issue with your script. Can you upload a sample of your data?

Please find the grib2 files attached. I am trying to convert the attached grib2 to dss
[grib2.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/8017128/grib2.zip)

**Comment by tombrauer** [comment]
@tharunpalla Can you test the file separator suggestion the @danhamill provided. This is a very common issue in Jython scripting.

**Comment by tharunpalla** [comment]
> @tharunpalla Can you test the file separator suggestion the @danhamill provided. This is a very common issue in Jython scripting.

Hi @tombrauer  and @danhamill, I have tried modifying the location string for shp file according to the suggestion but I am getting the same error.

Although, when I use a single variable as below

**Comment by danhamill** [comment]
I think that makes sense.  

Since .grib2 are self-describing data, you would only need select one variable (if they are all the same type of data).

**Comment by tharunpalla** [comment]
> 

Thank you.
