### ISSUE TITLE
Clipping data with shp

### ISSUE THREAD

**Issue by PowIlove** [HydrologicEngineeringCenter/Vortex#62]
hi @tombrauer its a pleasure to see each other again, i have other problem, this time is with clipping datasource, i was triying to clip my SHP of my watershed with that i'm working in my research and found this mistake, i adjunt the notepad with the error code.

PD: i was using the vortex version v0.10.27-rc.2 and files NLDAS type in format netCDF.

Regards.

[clipping error.txt](https://github.com/HydrologicEngineeringCenter/Vortex/files/8219651/clipping.error.txt)

**Comment by tombrauer** [comment]
Hi @PowIlove, I see the errors in your trace about a corrupted shapefile. I don't think Vortex is at issue here, rather I think the shapefile is bad for some reason. Are you able to open and view the shapefile in a GIS like QGIS?

**Comment by PowIlove** [comment]
yes, you're right, i review me shapefile in QGIS and found that don't appeared, check out it for yourself
![image](https://user-images.githubusercontent.com/59849903/157971975-ebabc9e9-1805-44d4-a3b8-9190a40e687c.png)

and later i checked in arcmap and look this error message
![image](https://user-images.githubusercontent.com/59849903/157972151-08356fa1-42b5-41db-ab1c-af0f4c86e8d1.png)

my file is corrupted
