### ISSUE TITLE
Range in Temperature files through NLDAS data

### ISSUE THREAD

**Issue by PowIlove** [HydrologicEngineeringCenter/Vortex#63]
Hi @tombrauer , in this occasion i'm having details with temperature dss files: i found a unusual detail with ranges of dates in the files into dss file, attached a picture to one better interpretation

![image](https://user-images.githubusercontent.com/59849903/159198627-48ca11b6-7220-416d-992f-b517110ec339.png)

Regards.

**Comment by tombrauer** [comment]
@PowIlove from the image you have provided, I don't see any issues. Temperature data is usually INST-VAL. By convention, INST-VAL grids have a D-part and no E-Part. The C-Part is "TEMPERATURE".
