### ISSUE TITLE
Feature Request: Specify number of CPU's available for processing

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#7]
It would be a nice feature if you could specify the number of CPU's available for processing when using 'importer`.   I have been crunching through a lot of hourly data and my CPU is ~100% allocated while data are being processed.

**Comment by tombrauer** [comment]
The code currently uses the max number of cores available to the JVM. You can control this setting on launch by using `-XX:ActiveProcessorCount=nn`. 

The *.bat file would look something like this:

```SET "PATH=.\gdal;%PATH%"
SET "GDAL_DRIVER_PATH=.\gdal\gdalplugins"
SET "GDAL_DATA=.\gdal\gdal-data"
SET "PROJ_LIB=.\gdal\projlib"
"..\jre\bin\java.exe" -XX:ActiveProcessorCount=2 -Djava.library.path=".;.\gdal" -cp ..\lib\importer.jar;..\lib\* importer.MetDataImportWizard```
