### ISSUE TITLE
Shifted gridded precipitation

### ISSUE THREAD

**Issue by DarioRuggiu** [HydrologicEngineeringCenter/Vortex#80]
Hi, 
I'm importing from netcdf files climatic dataset. The reference system of netcdf files is UTM wgs84 32N. I use import and every thing is good except the position of the data which are shifted to right. 
Do you have any idea to correct this issue?

**Comment by tombrauer** [comment]
@DarioRuggiu can you post a sample file so that I can investigate?

**Comment by DarioRuggiu** [comment]
The size of netcdf files is 2,5 gb and the dss file is close to 200 mb. I can just attach an image of the real coverage of netcdf dataset. If you give me an email I will send you a gd link which contains dss and netcdf data.
![Immagine 2023-04-21 090859](https://user-images.githubusercontent.com/40866214/233566011-13fa18db-baf4-4f60-a9c3-b7cc0ca721f1.png)

**Comment by tombrauer** [comment]
@DarioRuggiu you can email to thomas.brauer@usace.army.mil

**Comment by DarioRuggiu** [comment]
Thank you! Check your email!

**Comment by tombrauer** [comment]
@DarioRuggiu please test [v0.10.36-rc.1](https://github.com/HydrologicEngineeringCenter/Vortex/releases/tag/v0.10.36-rc.1).

The Rotated Pole projection that your data uses poses many challenges. See [NetCDF rotated grid support](https://lists.osgeo.org/pipermail/gdal-dev/2020-April/052003.html). I tried to add better support for Rotated Pole in Vortex. GDAL's support for the projection is still limited, at least in the Java API.

**Comment by DarioRuggiu** [comment]
Thanks Tom, the new release works fine! I will take further tests on different areas.
Thank you for your support and for the new Vortex version!
